<?php   
    $d = date ('d/m/y') ;
    echo $d . "<br>";
    $d2 = date ('d/M/Y') ;
    echo $d2 . "<br>";
    $d3 = date ('d/m/Y') ;
    echo $d3 . "<br>";
    $d4  = date ('l , F - Y') ;
    echo $d4 . "<br>";
    $d5 = date ('d/m/y', strtotime ('+10 day')) ;
    echo $d5 . "<br>";
    $d6 = date (strtotime ('+30 day')) ;
    echo $d6 . "<br>";
    $d7 = date ('d/m/y', $d6 ) ;
    echo $d7 . "<br>";
    $d8 = mktime (12 , 30 ,00 ,06 , 12 ,95) ;
    echo $d8 . "<br>";
    $nasci = date ('d/m/y' , $d8) ;
    echo $nasci . "<br>";
    $d9 = new DateTime ();
    print_r($d9) . "<br>";
    echo $d9->format('d/m/y') . "<br>";
    echo $d9->format('D /M /Y') . "<br>";
    $d9->modify('+5 year');
    echo $d9->format('D /M /Y') . "<br>";
    $d9->setDate(2000,12,01);
    print_r($d9) ;echo "<br>";
    $d9->setTime(5,12,01);
    print_r($d9) ;echo "<br>";
    $d10 = new DateTime();
    $diff = $d9->diff($d10);
    print_r($diff); echo "<br>";